# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

# Auto-generated by generate-deps.sh — do not edit

$(FETCH_PATH)/.nginx.1.31.6.stamp: .container/compile-gcc/deps/nginx/url.deps .container/compile-gcc/deps/nginx/version.deps
	M6E_DEPS_STAGE=compile-gcc .makefile/container/scripts/fetch.sh nginx
	touch $@

.container/compile-gcc/deps/nginx/hash.deps: $(FETCH_PATH)/.nginx.1.31.6.stamp
	M6E_DEPS_STAGE=compile-gcc .makefile/container/scripts/update-hash.sh nginx

PREREQUISITES += .container/compile-gcc/deps/nginx/hash.deps

